name: news_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # 日期格式
  intl: ^0.18.1

  # 屏幕适配
  flutter_screenutil: ^5.8.4

  # toast
  fluttertoast: ^8.2.2

  # http
  dio: ^5.2.1+1
  cookie_jar: ^4.0.5
  dio_cookie_manager: ^3.1.0

  # storage + cache
  shared_preferences: ^2.2.0
  localstorage: ^4.0.0+1
  cached_network_image: ^3.2.3

  # sha
  crypto: ^3.0.3

  #状态管理
  provider: ^6.0.5

  #ui
  flutter_easyrefresh: ^2.2.2

  #骨架屏
  pk_skeleton_null_safe: ^0.0.2

  #路由器
  auto_route: ^7.7.1


  # loading
  loading_animations: ^2.1.0

  # webView
  webview_flutter: ^4.2.2

  # 分享
  share_plus: ^7.0.2

  # logo图标
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.2.0
  build_runner:
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400 # normal
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
